#!/bin/bash

MYSQL_USER="root"
MYSQL_PASSWORD="t1477bcm"

function restore() {
	echo $1;
	(
        echo "SET AUTOCOMMIT=0;"
        echo "SET UNIQUE_CHECKS=0;"
        echo "SET FOREIGN_KEY_CHECKS=0;"
        cat "$1.sql"
        echo "SET FOREIGN_KEY_CHECKS=1;"
        echo "SET UNIQUE_CHECKS=1;"
        echo "SET AUTOCOMMIT=1;"
        echo "COMMIT;"
	) | mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$1"
}

restore
